# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9cd4887109017f2ff55a993b31622a8c9a402cc32be51889ace4ef2a0d1d33d32ba286cf762a41f19cbd6fdd3372e01c36ef98114b89a61127431f2bd24f4af

test:
  secret_key_base: 3114d7e4542ee7108c0b5a85f60763d343ccfde9835abb13363904b4f7a90866636bc9a25e6173c9f939c6dac9f994dc7fc98330b7583666904c82e5903a6da9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
